version: "3"

services:
  nextjs:
    container_name: nextjs
    build:
      context: .. # root of the project
      dockerfile: docker/next/Dockerfile
    env_file:
      - ../.env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: database
    build:
      context: .. # root of the project
      dockerfile: docker/mysql/Dockerfile # specify the path to your custom Dockerfile
    image: custom-mysql:8.0 # optionally specify a custom image name
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
